//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Prilozi
    {   [Key]
        public int PrilogID { get; set; }
        public int SednicaID { get; set; }
        public int DokumentID { get; set; }
        public string NazivPriloga { get; set; }
        public string Putanja { get; set; }
        public Nullable<bool> Poslato { get; set; }
        public Nullable<System.DateTime> DatumSlanja { get; set; }
    
        public virtual VrsteDokumenata VrsteDokumenata { get; set; }
        public virtual Sednice Sednice { get; set; }
    }
}
